# base image
FROM {{ TEMPLATE_BASE_IMAGE }}

USER root

# install ros
# setup timezone and get installation deps
RUN apt-get update && \
    apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2  && \
    rm -rf /var/lib/apt/lists/*

# setup keys
RUN set -eux; \
    key='{{ TEMPLATE_ROS_REPO_KEY }}'; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
    mkdir -p /usr/share/keyrings; \
    gpg --batch --export "$key" > /usr/share/keyrings/{{ TEMPLATE_ROS_GENERATION }}-latest-archive-keyring.gpg; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME"

# setup sources.list
RUN echo "deb [ signed-by=/usr/share/keyrings/{{ TEMPLATE_ROS_GENERATION }}-latest-archive-keyring.gpg ] http://packages.ros.org/ros/ubuntu {{ TEMPLATE_UBUNTU_CODENAME }} main" > /etc/apt/sources.list.d/{{ TEMPLATE_ROS_GENERATION }}-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO {{ TEMPLATE_ROS_VERSION }}

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-base \
    build-essential \
    python3-rosdep \
    python3-vcstools \
    {% if TEMPLATE_ROS_GENERATION == 'ros1' %}
    python3-rosinstall \
    {% else %}
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    {% endif %}
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init
# update rosdep
USER ${NB_UID}
RUN rosdep update --rosdistro $ROS_DISTRO

{% if TEMPLATE_ROS_GENERATION == 'ros2' %}
# setup colcon mixin and metadata
RUN colcon mixin add default \
      https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update && \
    colcon metadata add default \
      https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
    colcon metadata update
{% endif %}

# Source the ROS setup file
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
